#' read_star
#'
#' Reads out.tab files generated by STAR aligner.
#'
#' @param file name of STAR out.tab file.
#'
#' @return
#' @export
#'
read_star <- function(file = NULL) {
  d <- read_tsv(file, col_names = FALSE, skip = 4,
    col_types = c(
      X1 = col_character(),
      X2 = col_double(),
      X3 = col_double(),
      X4 = col_double()
    )
  )
  d %>% rename(
    id = 1,
    unstranded = 2,
    fr_strand = 3,
    sr_strand = 4
  )
}
